export const SPLASH_ASSET_KEY = {
  SPLASH: "SPLASH_ASSET_KEY_SPLASH",
};

export const IMAGE_ASSET_KEY = {
  BACKGROUND: "IMAGE_ASSET_KEY_BACKGROUND",
  BACKGROUND_INGAME: "IMAGE_ASSET_KEY_BACKGROUND_INGAME",
  CHARACTER_1: "IMAGE_ASSET_KEY_CHARACTER_1",
  CHARACTER_2: "IMAGE_ASSET_KEY_CHARACTER_2",
  CHARACTER_3: "IMAGE_ASSET_KEY_CHARACTER_3",
  CHARACTER_4: "IMAGE_ASSET_KEY_CHARACTER_4",
  LOADING_HELPER: "IMAGE_ASSET_KEY_LOADING_HELPER",
  QUESTION_HELPER: "IMAGE_ASSET_KEY_QUESTION_HELPER",
  WINNER_HELPER: "IMAGE_ASSET_KEY_WINNER_HELPER",
  LOSER_HELPER: "IMAGE_ASSET_KEY_LOSER_HELPER",
  BUTTON_O_OFF: "IMAGE_ASSET_KEY_BUTTON_O_OFF",
  BUTTON_O_ON: "IMAGE_ASSET_KEY_BUTTON_O_ON",
  BUTTON_X_OFF: "IMAGE_ASSET_KEY_BUTTON_X_OFF",
  BUTTON_X_ON: "IMAGE_ASSET_KEY_BUTTON_X_ON",
  BUTTON_JOIN: "IMAGE_ASSET_KEY_BUTTON_JOIN_OFF",
  BUTTON_REFRESH: "IMAGE_ASSET_KEY_BUTTON_REFRESH",
};
